"""Regenerate /tmp/moe_sweep_stat.md from the persisted grid + permutation results."""
import os
import numpy as np, pandas as pd
OUT = "/home/jovyan/work/himoe-vla/analysis_stat_axis"
MD = "/tmp/moe_sweep_stat.md"
L = []
def w(s=""): L.append(s)

g = pd.read_csv("/tmp/moe_sweep_stat.csv")
perm = pd.read_csv("/tmp/moe_sweep_stat_permutation.csv")
pw = pd.read_csv("/tmp/moe_sweep_stat_permutation_pointwise.csv")

w("# Statistic-axis sweep - MoE routing failure detection")
w()
w("Axis: **which scalar quantity to extract**, slice held fixed. COMPLETE.")
w()
w("- Main sweep slice: HB layers 12-15, action tokens 1-10, denoise step 9.")
w("- Check slice: HB layers 2-5, state token 0, denoise step 9.")
w("- 67 statistics x 5 t x 2 slices x 2 corpora = 1284 cells, all in `/tmp/moe_sweep_stat.csv`.")
w("- `auc` = P(score higher | success), reported raw. `auc_failure` = 1-auc. Oriented AUC = max(auc,1-auc).")
w("- Within-group pooled by pair count. Group = worker (A: 3/4 workers have both classes; worker 1 is 0/80 success")
w("  and contributes 0 pairs) / init_state_id (B: 13/16 groups; 33,36 are 32/32, 49 is 0/32).")
w("- Risk set T>t. A: n_pos=117 n_neg=155 (2933 pairs) for t<=30; at t=35 A loses 20 successes and 0 failures")
w("  -> **A t=35 is survivorship-contaminated, do not quote** (A t=35: 97/155). B: n_pos=232 n_neg=184 (2008 pairs),")
w("  and B loses only 1 success going to t=35 (231/184, 1990 pairs), so B t=35 is usable.")
w("- Baseline `H:hel_prev_mean_W8` main slice reproduced at A 0.799 / B 0.751 (target 0.795 / 0.759).")
w("- No hard top-4 expert IDs or set-overlap anywhere; probability vectors only. `I:top4mass` is the *sum of the")
w("  4 largest probabilities*, a continuous function of p, identical to sum(hb_selected_prob) to 0 ulp.")
w()
w("## 0. Headline answers")
w()
w("Every family is priced **twice**: RAW, and RESIDUALISED. The raw family *contains the pre-existing")
w("baseline* (`H:hel_prev_mean_W8`, main slice), so a raw family-wise p only certifies that the baseline")
w("clears the null. The residualised family rank-residualises every statistic, within group, on that baseline")
w("before taking the AUC, and asks the real question: does this statistic carry anything the baseline does not")
w("already have? Sanity: the baseline residualised on itself gives exactly 0.500 in both corpora.")
w()
w("**RESIDUALISED VERDICT ON THE TWO HEADLINE CELLS: they shrink hard, and only partly survive.**")
w("`H:hel_prev_mean_W12 | front` 0.815 -> **0.655** (A) and 0.777 -> **0.682** (B);")
w("`H:ewm_rate_a0.15 | main` 0.800 -> **0.604** (A) and 0.776 -> **0.634** (B).")
w("Both lose 55-70% of their excess over 0.5, confirming your read that they are longer-memory restatements of")
w("the baseline. What is left is real but small: point-wise at t=30 both are p<=0.045 in both corpora with the")
w("*same* direction (more routing change -> success), so lengthening the memory from W=8 to W=12-13 does add a")
w("genuine increment. But it does **not** clear family-wise: the residualised self-referential family in corpus A")
w("gives p=0.110 (obs 0.675 vs null p95 0.683), and A's best residual cell in that family is not W12 at all")
w("(it is `H:hel_to_winmean_W5` at t=20). Corpus B's residualised self-referential family does clear (p=0.005)")
w("but its top cell is `H:acf_lag3|front`, a different statistic. Verdict: **memory length is a point-wise real,")
w("family-wise unproven, corpus-inconsistent effect.** Do not promote W=12 over W=8 on this evidence.")
w()
w("**Cross-corpus sign agreement of the residuals, t<=30, 508 cells: 64.6%** (raw, un-residualised: 69.9%;")
w("chance 50%). By family: reference 72.5%, self-referential historical 61.9%, instantaneous 58.9%. So after")
w("the baseline is removed the reference family is by far the most reproducible thing on this axis, and the")
w("instantaneous family is barely distinguishable from chance.")
w()
w("**(a) Instantaneous, history-free statistics: NO.** The best history-free scalar is `I:tok_heterog`")
w("(mean Hellinger of each action token's routing vector to the 10-token mean) at 0.645 A / 0.722 B (t=30),")
w("but family-wise over the 112-cell instantaneous family at t<=30 it gives **p=0.174 in corpus A** (null p95 0.668)")
w("and p=0.005 in B - it fails in the primary corpus, so the instantaneous family is a clean negative;")
w("every classic sharpness scalar (entropy, top-1, top-4 mass, 4th-5th gap, KL/Bhattacharyya to uniform, Gini,")
w("participation ratio, and their across-token dispersions) sits in 0.46-0.55 in corpus A at t=30.")
w("Residualised it is worse still: family-wise **p=0.597 in A** (obs 0.619 vs null p95 0.677) and p=0.015 in B on")
w("a different statistic, with only 58.9% cross-corpus sign agreement. No history-free statistic works. Plainly negative.")
w()
w("**(b) Reference-to-others'-successes family: YES, it is the best thing on this axis - but it buys labels.**")
w("`R:succ_minus_fail_ref_W12` reaches **0.914 A / 0.817 B** and `R:hel_to_succ_ref_W8` **0.871 A / 0.791 B**,")
w("both beating the 0.795/0.759 self-referential baseline in both corpora (family-wise p=0.005, the 200-draw floor);")
w("but it is a cross-fitted supervised nearest-centroid score, its *label-free* twin `R:hel_to_cohort_LOO_W8`")
w("collapses (0.705 A / 0.431 B), and on the front/state-token slice the reference family loses to the")
w("plain self-referential change rate. It is a better detector, not a better signal. **It is, however, the only")
w("family that survives residualisation in both corpora with a consistent identity**: `R:succ_minus_fail_ref_W8/W12`")
w("and `R:hel_to_succ_ref_W8` hold residual oriented AUC 0.70-0.77 at t=25 and t=30, p=0.005-0.010 point-wise AND")
w("family-wise in A and B, same direction, 72.5% sign agreement. Whatever it is reading, the baseline does not")
w("already contain it.")
w()

for sl in ["main", "front"]:
    for corp in ["A", "B"]:
        d = g[(g.slice == sl) & (g.corpus == corp)]
        pv = d.pivot_table(index=["family", "statistic"], columns="t", values="auc")
        cols = [c for c in pv.columns if c in (15, 20, 25, 30)]
        pv["maxdev_t<=30"] = (pv[cols] - .5).abs().max(axis=1)
        w(f"## corpus {corp} / slice {sl}   (t=35 column shown but censored in A)")
        w()
        w("```")
        w(pv.sort_values("maxdev_t<=30", ascending=False).round(3).to_string())
        w("```")
        w()

w("## Cells beating the 0.795 / 0.759 baseline in BOTH corpora at t=30 (oriented AUC)")
w()
d = g[g.t == 30].copy(); d["o"] = np.maximum(d.auc, 1 - d.auc)
p = d.pivot_table(index=["slice", "family", "statistic"], columns="corpus", values="o")
p["min"] = p[["A", "B"]].min(axis=1)
w("```")
w(p[(p.A > 0.795) & (p.B > 0.759)].sort_values("min", ascending=False).round(3).to_string())
w(f"\n{len(p)} statistic x slice cells evaluated at t=30 on this axis; 11 clear the bar in both corpora.")
w("```")
w()
w("## Permutation null - within-group branch-level label permutation, 200 draws")
w()
w("RAW vs RESIDUALISED, t<=30 (the quotable restriction). Residualisation is on `H:hel_prev_mean_W8`, main slice,")
w("rank-regressed within group; the same main-slice baseline is used for the front-slice statistics too, since")
w("that is the pre-existing baseline being defended. Nulls: `/tmp/perm_null_stat_{A,B}.npy` (raw) and")
w("`/tmp/perm_null_resid_{A,B}.npy` (residual), each 200 x 642. Per-cell values: `/tmp/moe_sweep_stat_residual_cells.csv`.")
w()
w("```")
w(perm[perm.family.str.endswith(("RAW", "RESIDUALISED"))]
  [["corpus", "family", "obs", "p", "null_p95", "null_max", "best_stat", "best_slice", "best_t", "n_cells"]]
  .to_string(index=False))
w("```")
w()
w("Shrinkage at t=30, oriented AUC (raw -> residual):")
w()
w("```")
w(pd.read_csv("/tmp/moe_sweep_stat_residual_cells.csv").query("t==30")
  .pivot_table(index=["slice","statistic"], columns="corpus",
               values=["oriented_raw","oriented_resid"]).round(3).to_string())
w("```")
w()
w()
w("One permutation per draw, applied at branch level within group, reused across ALL t and BOTH slices so the")
w("nesting of the risk sets is preserved. Family statistic = max oriented AUC over the family. p = (1+#{null>=obs})/201,")
w("floor 0.0050. Nulls: `/tmp/perm_null_stat_A.npy` / `_B.npy` (200 x 642 full permuted grids).")
w()
w("```")
w(perm[perm.family.str.contains("two_sided")]
  [["corpus", "family", "obs", "p", "null_p95", "null_max", "null_med", "best_stat", "best_slice",
    "best_t", "n_cells"]].to_string(index=False))
w("```")
w()
w("Point-wise pricing of the individual cells of interest (no family max):")
w()
w("```")
w(pw.to_string(index=False))
w("```")
w()
w("Leak check on the cross-fitted reference family: mean permuted AUC per cell is 0.5065 (A) / 0.5088 (B),")
w("worst single cell +0.039; the H: and I: families sit at 0.498-0.503. The cross-fitting is essentially clean,")
w("the small residual is fully absorbed by the permutation null (null medians 0.65 A / 0.61 B, not 0.9).")
w()
w("## Not tested / caveats")
w()
w("- The coordinator's 646-cell four-axis selection is NOT corrected here; my family-wise p is a within-axis")
w("  lower bound. The observed 0.914 A / 0.840 B sit far above the *whole-axis* null max (0.785 / 0.759), so a")
w("  4x wider family would not change the verdict, but the exact p would rise above the 0.0050 floor.")
w("- 200 draws floors p at 0.0050; nothing here can be resolved finer.")
w("- Residualisation is rank-linear only: it removes the monotone component shared with the baseline, not any")
w("  non-monotone dependence. A statistic could still be a nonlinear re-expression of the baseline and survive.")
w("- The residualised comparison is not apples-to-apples across families: the R: family is a *supervised*")
w("  cross-fitted score residualised on a *label-free* baseline, so part of its residual advantage is simply")
w("  that it is allowed to consume labels the baseline never sees. It answers \"is there more signal here\",")
w("  not \"is there a better deployable statistic here\". Only the H:/I: residuals are like-for-like.")
w("- I did not residualise on anything other than the single pre-existing baseline (e.g. on the best statistic,")
w("  or jointly on several), and I did not test forward selection or any multivariate combination.")
w("- Denoise step held at 9 throughout; no sweep over the other 9 flow-denoise iterations, and no statistic that")
w("  uses the *within-chunk* denoise trajectory (10 steps) as its history instead of the control-step history.")
w("  That is the one untested source of a genuinely history-free signal - a single inference call already")
w("  contains a 10-step internal trajectory, so a within-call denoise-drift statistic needs no buffer.")
w("- Cells were aggregated by an unweighted mean over the 4 layers x 10 tokens; no learned or per-cell weighting,")
w("  no multivariate combination of statistics, no calibration/threshold analysis - AUC only.")
w("- The reference family used class means (centroids) only; no covariance/Mahalanobis, no k-NN to individual")
w("  successful branches, no reference pooled across groups or across neighbouring query indices.")
w("- Statistics were evaluated at 5 fixed t; no time-to-detection, no sequential/CUSUM stopping rule.")
w("- `I:kl_p_unif` is exactly affine in `I:ent_norm` (KL(p||u) = log32 - H(p)) so its AUC is the mirror of entropy")
w("  by construction; it is reported for completeness, not as an independent test.")
w("- Confound worth naming: at t=30 a success branch is ~80% through its episode and a failure ~60% through")
w("  (A successes end at T=33-46, failures at T=47-52). Everything on this axis, baseline included, is partly")
w("  reading task phase. The reference family reads it most directly - it is close to an on-schedule detector.")
w("- Corpus A group = worker, which is the pre-registered grouping; init_state_id is also present in the label")
w("  file and was not used as an alternative grouping.")
w()
open(MD, "w").write("\n".join(L))
print("wrote", MD, len(L), "lines")
